module.exports = [

  "Sua empresa está bem preparada nesta área. Onde apropriado, a estrutura de governança deve fazer referência a políticas e procedimentos existentes vinculados ao processamento de dados pessoais (por exemplo, a política de segurança da informação ou a política de gerenciamento de identidade e acesso). Da mesma forma, organização e conceitos técnicos, uma estrutura e disposições de governança devem ser referenciadas para garantir a consistência (por exemplo, quaisquer esquemas de classificação de dados existentes ou a determinação dos níveis de proteção de ativos de informação). ",

  'Os elementos de governança em torno de um registro de processamento incluem, mas não estão limitados a: \n • Ativos de informações usados ​​(do registro de dados pessoais) \n • Objetivo (s) de processar Processos de negócios ou outros processos organizacionais que utilizam os ativos \n • Vida útil do processamento ciclo da aquisição inicial de dados à exclusão de dados (planejado ou ad hoc) \n • O processo de governança em torno do registro de processamento deve definir ainda mais uma função ou função responsável por manter o registro, bem como a acessibilidade do registro para análises internas e externas. Outras disposições de governança podem incluir o escopo e o procedimento para apresentar o registro como evidência, interna e externamente. Em situações em que o processamento complexo de grandes quantidades de dados pessoais ocorra, o registro deve ser regido por uma política ou procedimento operacional chave apropriado. ',


  "Sua empresa está indo bem nesta área. Uma empresa deve estabelecer, manter, monitorar e adaptar continuamente regras corporativas vinculativas que reflitam de maneira adequada e abrangente a estrutura de governança interna e externa. As atividades em conjunto com os BCRs incluem, mas não estão limitadas a: \n • Definição, descrição e aprovação de BCRs pela alta administração \n • Comunicação de BCRs em toda a empresa \n • Validação e atualização anual ou ad hoc de BCRs \n • Integração de BCRs em relacionamentos contratuais de terceiros \n • Monitoramento de conformidade com a BCR interna e externamente ",

"As regras de consentimento da sua empresa são bem definidas e comunicadas. No mínimo, as disposições de governança relacionadas ao consentimento devem abranger: \n • Transparência e permitir informações aos titulares dos dados \n • Tipos de consentimento e requisitos relacionados \n • Retirada do consentimento por titulares dos dados \n • Processos, controles e verificações específicas para consentimento da criança, incluindo verificação apropriada da idade e / ou autoridade dos pais, bem como canais de comunicação dos pais, simplicidade de linguagem e acessibilidade de interfaces baseadas em consentimento ",


"Sua empresa está bem equipada para processar solicitações de titulares de dados. No mínimo, as disposições de governança relacionadas às solicitações de titulares de dados devem abranger: \n • Receber e documentar solicitações de titulares de dados \n • Validação de solicitações relacionadas a objetivos, legal e técnica \n • Resposta formal, incluindo canais e formatos de comunicação \n • Interfaces com processos internos e da cadeia de suprimentos \n • Interface para registro de dados pessoais e registro de processamento \n • Revisão independente de solicitações pela função DPO ",


"Sua empresa é eficaz no tratamento de reclamações dos titulares de dados. No mínimo, as disposições de governança relacionadas às reclamações dos titulares de dados devem abranger: \n • Recebimento e documentação inicial, incluindo qualquer resposta formal às autoridades de supervisão \n • Análise de reclamações, incluindo organização, interfaces técnicas e legais dentro da empresa \n • Definição e implementação de remediação, quando aplicável \n • Identificação de possíveis lacunas ou deficiências que levem à reclamação e oportunidades de melhoria ",


"Sua empresa possui um processo bem governado para garantir uma supervisão imparcial. As atividades em conjunto com a supervisão imparcial incluem, mas não estão limitadas a: \n • Funções organizacionais que desempenham e garantem uma supervisão imparcial \n • Funções e responsabilidades (RACI), incluindo demonstrações imparcialidade \n • Objetivos, escopo e extensão das atividades de supervisão \n • Frequência baseada em risco das atividades de supervisão \n • Procedimentos e orientações para o planejamento, implantação e elaboração de relatórios ",




"Sua empresa está bem preparada nesta área. No mínimo, as seguintes partes do ciclo devem ser definidas e implementadas: \n • Criação ou aquisição de dados, incluindo a cadeia de processamento de dados pessoais (fornecimento) \n • Classificação de ativos de informações , incluindo níveis de proteção e atribuição a categorias especiais \n • Inclusão no registro de dados pessoais e no processamento e remoção de registros \n • Processamento real e controles relacionados \n • Armazenamento temporário e permanente, incluindo armazenamento virtualizado e em nuvem \n • Arquivamento e agregação \n • Exclusão, planejada (fim da vida útil ou fim da finalidade) e ad hoc (solicitação de apagamento etc.) ",


"Sua empresa está realizando um excelente trabalho de identificação e documentação de dados pessoais. O processo de identificação deve, no mínimo, abordar os seguintes aspectos: \n • Definição de critérios de acordo com os regulamentos estabelecidos de privacidade e proteção de dados \n • Procedimento para analisar dados existentes conjuntos, possivelmente em combinação com a análise dos níveis de proteção de segurança (CIA) \n • Procedimento de entrega para registro de dados pessoais \n • Análise de inferência em potencial (identificação indireta de pessoas físicas) de conjuntos de dados separados e / ou dispersos \n • Onboarding procedimento para novos dados \n • Procedimentos e controles para terceiros ",



"Sua empresa é eficaz na manutenção da classificação de dados. No mínimo, a classificação de dados pessoais deve abordar: \n • Atributo geral de pessoal de acordo com os regulamentos estabelecidos de privacidade e proteção de dados; maior relevância pessoal como PII, se necessário \n • Específico classificação relacionada a categorias e finalidades especiais, incluindo limitações e requisitos adicionais de segurança \n • Classificação em termos de não repúdio de transações envolvendo dados pessoais \n • Outros aspectos, como sigilo profissional aplicável ou critérios de acesso restrito ",




"O registro de dados pessoais da sua empresa é muito bem mantido. No mínimo, o processo de registro de dados pessoais deve tratar: \n • Tipo de dados e agregação (se houver) em ativos de informações \n • Links relevantes entre conjuntos de dados que formam informações ativos sob regulamentos estabelecidos de privacidade e proteção de dados \n • Tipos e formatos de dados, incluindo dados não mantidos em formatos eletrônicos (por exemplo, papel, microficha) \n • Localização e instanciação de dados, incluindo várias cópias, imagens virtualizadas e em nuvem, etc. \n • Informações sobre o ciclo de vida e o tempo de vida útil, incluindo arquivamento e exclusão planejados \n • Etapas de processamento vinculadas, unidades organizacionais e finalidades de processamento, detalhando claramente quando, por que, onde e por quem do processamento de dados pessoais ",


"Sua empresa está bem equipada para gerenciar dados de categorias especiais. Isso requer um processo robusto que identifica, controla e documenta qualquer processamento de dados pertencentes a uma ou mais categorias especiais, cobrindo no mínimo, mas não limitado a: \n • Mapeamento de ativos de informações identificados para categorias especiais de acordo com os regulamentos estabelecidos de privacidade e proteção de dados \n • Documentação de circunstâncias justificativas (conforme os regulamentos estabelecidos de privacidade e proteção de dados) para cada ativo de informações \n • Documentação de qualquer classificação nova ou alterada dessas informações NOTA: • Documentação de todas as comunicações com os titulares dos dados ou autoridades de supervisão relacionadas ao ativo de informação \n • Documentação do consentimento relacionado ao ativo e retirada do consentimento \n • Links verificados para o registro de dados pessoais e registro de processamento, incluindo evidências de processamento restrito ao (s) objetivo (s) definido (s) ",


"Sua empresa está bem preparada para responder às demandas de apagamento. O processo deve, no mínimo, abordar os seguintes aspectos: \n • Recebimento, confirmação e análise de solicitações de apagamento por titulares de dados ou autoridades competentes \n • Validação e internalização solicitações de apagamento transferidas por terceiros \n • Interfaces definidas para outros processos, ou seja, registro de dados pessoais e \n registro de processamento, classificação e ciclo de vida dos dados \n • Aprovações e procedimentos de verificação independente em torno do apagamento \n • Confirmação e comunicações de apagamento procedimento (para titulares ou autoridades de dados) ",



"Sua empresa realizou uma avaliação de risco completa. Como lembrete, os resultados da avaliação de risco devem incluir, no mínimo: \n • Registro abrangente de eventos e ameaças que conduzam a categorias estabelecidas de risco de privacidade e proteção de dados \n • Estimativas de frequência e premissas de precaução \n • Agregação e agrupamento de eventos que levam aos mesmos riscos que se materializam \n • Classificação de risco, geralmente de acordo com o esquema organizacional de classificação \nrisk abrangente ",


"Sua empresa conduziu com sucesso uma avaliação de impacto na proteção de dados. Como lembrete, o DPIA deve levar em consideração os controles e medidas de mitigação de riscos existentes e ter como objetivo identificar o impacto potencial resultante do risco residual que não foi ou não pode ser totalmente mitigado. . ",


"Sua empresa está fazendo um excelente trabalho gerenciando o tratamento de riscos. Como lembrete, o processo de tratamento de riscos deve, no mínimo, abranger o seguinte: \n • Evitar ou eliminar riscos, incluindo alterações nas disposições do processamento ou descontinuação do processamento (reestruturação ou saída) \n • Eliminação de riscos por meio de controles ou salvaguardas adicionais \n • Transferência de riscos, incluindo a reestruturação da cadeia de fornecimento de dados pessoais \n • Redução de riscos por meio de controles adicionais ou medidas de mitigação \n • Tolerância a riscos, com base na frequência e impacto estimados ",


"Sua empresa possui um processo de validação robusto. Como um lembrete, no mínimo, o processo de validação de risco deve abordar: \n • Confirmação (ou alteração) dos resultados da avaliação de risco, incluindo estimativas de frequência e período razoável de observação do universo de eventos / ameaças \n • Revisão de quaisquer incidentes ou violações que possam ter ocorrido desde a última validação \n • Análise de quaisquer alterações na estrutura e nos termos de referência, ou seja, em relação a qualquer evento legislativo ou regulatório, político ou financeiro ",



"Sua empresa está fazendo um excelente trabalho nesta área. O anonimato e a pseudonimização devem abranger, mas não estão limitados a: \n • Identificação de conjuntos de dados pessoais a serem anonimizados / pseudonimizados \n • Definição de técnicas em todos os níveis técnicos, por exemplo, arquivo , registro de banco de dados, sistemas de arquivos não eletrônicos \n • Documentação e registro real de anonimização / pseudonimização \n • Link definido para registro de dados pessoais e registro de processamento \n • Aplicação recursiva do princípio da necessidade de conhecimento em toda a cadeia de suprimentos; integração de a necessidade real de conhecer o gerenciamento de identidades e acessos ",



"A estratégia de criptografia e seus componentes devem ser baseados em risco e eficiência, garantindo que os riscos estabelecidos de privacidade e proteção de dados sejam totalmente compreendidos e internalizados em qualquer decisão. Sua empresa está indo muito bem nessa área. Como lembrete, no mínimo , o processo de criptografia deve abordar: \n • Conjunto definitivo de dados pessoais e ativos de informações a serem criptografados, com base nos níveis de proteção atribuídos nas categorias estabelecidas de risco e impacto de privacidade e proteção de dados \n • Definição de técnicas e destinos de criptografia, por exemplo, dados individuais, elementos de banco de dados, bancos de dados inteiros, transações, etc. \n • Links para técnicas e ferramentas de criptografia reconhecidas ou aprovadas, já em uso na empresa \n • Escopo, planejamento e etapas de implementação para criptografia adicional necessária para dados pessoais ",


"Sua empresa está fazendo um excelente trabalho no gerenciamento dos níveis de proteção. O processo em torno dos níveis de proteção de dados pessoais fornece uma interface definida (nos dois sentidos) entre segurança geral das informações e segurança dos dados pessoais. Os profissionais e empresas do DPP devem refletir isso definindo interfaces organizacionais apropriadas para apoiar o fluxo de informações e a representação adequada dos dados pessoais nas análises do nível de proteção. ",


"Sua empresa possui um processo bem administrado para gerenciar a resiliência. Como um lembrete, no mínimo, o processo de resiliência deve abranger: \n • Criticidade de dados pessoais, geralmente expressa como uma combinação de requisitos de integridade e disponibilidade \n • Criticidade de processamento em função do tempo, ou seja, período máximo tolerável de indisponibilidade, perda máxima tolerável de dados \n • Planos de recuperação para conjuntos de dados pessoais \n • Links definidos para continuidade geral de negócios e planos de continuidade de serviços de TI \n • Backup e restauração de conceitos para pessoal conjuntos de dados, vinculados a planos e procedimentos gerais de backup e restauração \n • Múltipla instanciação de conjuntos de dados pessoais que exigem alta disponibilidade, ou seja, processamento \nfully resiliente ",



"Sua empresa está gerenciando efetivamente o acesso aos dados pessoais. As restrições e limitações de acesso resultantes dos requisitos de processamento de dados pessoais devem ser documentadas e alimentadas no processo geral do IAM. O processo de gerenciamento de acesso aos dados pessoais fornece, portanto, uma interface (bidirecional) para o IAM geral Os profissionais e empresas de DPP devem refletir isso definindo interfaces organizacionais apropriadas para apoiar o fluxo de informações e a representação adequada de dados pessoais no gerenciamento de acesso. ",


"Sua empresa possui um processo robusto para gerenciar testes e avaliação da segurança de dados pessoais. Como lembrete, no mínimo, o processo deve abordar: \n • Tipos de teste e avaliação, por exemplo, teste conceitual, verificação de vulnerabilidades e penetração testes \n • Frequência dos testes \n • Evidências de melhoria contínua, isto é, testes e avaliações progressivamente mais exigentes ao longo do tempo \n • Registro e proteção de evidências de testes \n • Análise de fragilidades e documentação de oportunidades de melhoria ",



"Sua empresa possui um processo robusto para gerenciar controladores e processadores. Como lembrete, o processo deve abranger pelo menos: \n • Identificação de controladores primários e conjuntos, incluindo objetivos individuais ou coletivos para o processamento de dados pessoais \n • Identificação de processadores, incluindo o escopo definido e a extensão do processamento em nome de um ou mais controladores \n • Links para o registro de dados pessoais, refletindo os conjuntos de dados e a maneira como eles são tratados na cadeia de suprimentos (dados em fluxo; dados em repouso) \n • Links para o registro de processamento, refletindo os processos ou etapas do processo executados por cada ator na cadeia de suprimentos \n • Documentação das disposições de gerenciamento e controle de fornecedores (processadores), geralmente incorporadas ao gerenciamento geral de fornecedores de uma empresa ",



"Em cadeias de suprimentos complexas, o processo de gerenciamento de subprocessamento é um elemento essencial para garantir a conformidade dos regulamentos de privacidade e proteção de dados em toda a cadeia de suprimentos com as normas esperadas ou estabelecidas. Sua empresa está se saindo muito bem nessa área. Como lembrete, o gerenciamento de subprocessos o processo deve abranger, no mínimo: \n • Procedimento formal de solicitação para processadores primários; divulgação de qualquer terceirização adicional \n • Documentação e registro de subprocessamento, incluindo escopo, extensão e finalidade (s) \n • Evidência de conformidade com a privacidade estabelecida e regulamentos ou normas de proteção de dados, incluindo processos, controles, conceitos e resultados da revisão \n • Relatórios de auditoria e outras garantias independentes, se disponíveis \n • Processamento de contratos entre processadores primários e subprocessadores ",



"Sua empresa está indo bem nesta área. Como um lembrete, no mínimo, o processo em torno desses acordos deve abranger: \n • Definição, aprovação e implementação de acordos padronizados, incluindo modelos \n • Monitoramento do cumprimento de um contrato. base regular \n • Planejamento e execução de revisões, principalmente sob o direito padrão de auditoria \n • Recebimento, análise e validação de evidência de terceiros para processamento conforme, por exemplo, relatórios de certificação e atestado \n • Revisão e atualização regulares do processamento acordos, termos e condições, de acordo com a atividade legislativa e reguladora \n • Planejamento de término e saída para relações contratuais individuais ",



"Sua empresa está bem preparada nessa área. Em uma cadeia de suprimentos com vários atores, os impactos resultantes dos riscos à privacidade e à proteção de dados podem se materializar a qualquer momento e a qualquer momento. Portanto, os profissionais e empresas do DPP devem aplicar sua própria abordagem de DPIA para: todas as partes da cadeia de suprimentos e documentam o feedback recebido de cada uma das partes, incluindo relatórios padronizados, revisões ad hoc ou verificações de plausibilidade. O impacto geral deve ser agregado, com base no registro de processamento e no fluxo de dados entre as partes. participantes da cadeia de suprimentos. Deve-se tomar cuidado para entender como os impactos em um local podem agravar os impactos em outras partes da cadeia de suprimentos. ",


"Onde o processamento de dados pessoais é realizado em uma cadeia de suprimentos, os controles internos de um processador ou subprocessador devem ser tão eficazes quanto os da organização controladora. O processo bem definido de controles da cadeia de suprimentos da sua empresa garante que esse seja o caso. , no mínimo, o processo de controles da cadeia de suprimentos deve abranger o seguinte: \n • Obtenção e análise de documentação de controles internos de terceiros \n • Mapeamento para o sistema de controle interno (ICS) na organização do controlador \n • Procedimentos para teste de projeto (ToD), isto é, técnicas padrão para avaliação de controles \n • Procedimentos para teste de eficácia (ToE), isto é, amostragem e coleta de evidências que demonstram a eficácia dos controles de terceiros \n • Monitoramento e revisão de logs, incluindo acessibilidade de dados de registro, na medida em que estejam relacionados ao processamento de dados pessoais \n • Direitos de auditoria pontuais ou contínuos, incluindo planejamento e implantação de auditoria ",


"Sua empresa está bem preparada para gerenciar a notificação em tempo hábil. Como lembrete, no mínimo, o processo de notificação das autoridades de supervisão deve incluir: \n • Procedimento de coleta / investigação de informações, descrevendo a interação entre a função DPO e outras partes da empresa e / ou serviços externos \n • Pacote de relatórios padronizado, incluindo os requisitos mínimos de conjuntos de informações sobre privacidade e proteção de dados e modelos apropriados ",


"Sua empresa está bem equipada para notificar os titulares de dados em caso de incidente ou violação. Como lembrete, no mínimo, o processo de notificação dos titulares de dados deve abranger: \n • Formato e modelos de relatório padronizados, adaptados e otimizados para vários canais de comunicação (individual, grupo, público) \n • Mensagens-chave predefinidas e aprovadas que expressam as ações da empresa (investigação, conseqüências, remediação, aprimoramento, etc.) \n • Responsabilidades organizacionais em relação à formulação e transmissão de mensagens-chave, por exemplo , envolvimento do departamento de comunicações, assessoria jurídica, etc. \n • Recursos de comunicação ad hoc oferecidos aos titulares dos dados, por exemplo, linha de ajuda, número de telefone gratuito, local escuro, etc. ",

"Sua empresa possui um processo bem definido de gerenciamento de incidentes e crises. Da perspectiva dos profissionais de DPP e das unidades organizacionais que descobriram inicialmente a violação, o processo deve abranger pelo menos: \n • Descrição e documentação de fatos e números conhecidos, de forma padronizada formato onde apropriado \n • Link definido para o processo geral de escalação e alerta, geralmente definido pela função de gerenciamento de crises de negócios (BCM) \n • Cenário de dados pessoais genéricos predefinidos para continuidade de negócios e gerenciamento de crises, semelhante a outros cenários especiais, como ataque cibernético, pandemia, etc. \n • Relacionamentos e canais de comunicação predefinidos com atores externos, isto é, serviços externos, como especialistas em investigação ou forenses \n • Protocolo de comunicação contínuo entre unidades de linha organizacional e equipes de gerenciamento de incidentes / crises ",



"Sua empresa está bem preparada para gerenciar evidências e reivindicações de forma adequada. As violações de dados pessoais representam casos de não conformidade, mas também indicam que negligência interna e / ou externa ou atividade criminosa pode estar presente. O processo de evidências e reivindicações deve, portanto, cobrir mínimo: \n • Procedimentos definidos para coletar e proteger evidências, incluindo cadeia de custódia \n • Disponibilidade de serviços especializados, como forense de TI \n • Procedimento e modelos para análise e relatório pós-incidente \n • Procedimento para fundamentar reivindicações contra terceiros , incluindo a base legal ou contratual de tais reclamações \n • Procedimento para preparar defesas contra reclamações de terceiros, incluindo aspectos de apelação (decisões regulatórias) \n • Link definido para relatar DPO incidente ",



"Sua empresa está fazendo um bom trabalho mantendo a conscientização da empresa. No mínimo, o processo de conscientização em toda a empresa deve abranger: \n • Definição e descrição dos requisitos de privacidade e proteção de dados nos processos organizacionais diários, incluindo exemplos de processamento de dados pessoais \n • Materiais da campanha enfatizando aspectos específicos do DPP, dados pessoais \nprocessamento e privacidade e pontos relacionados à proteção de dados a serem observados \n • Planos de programas / projetos que definem datas-alvo para medidas de conscientização \n • Materiais de conscientização de terceiros e detalhes sobre como incluir terceiros em campanhas de conscientização ",



"A proteção de dados e o gerenciamento de privacidade, incluindo o contexto de regulamentos estabelecidos de privacidade e proteção de dados, exigem um conjunto de habilidades e qualificações que devem estar presentes na empresa ou contratadas por meio de serviços externos. O gerenciamento de habilidades e educação é um processo essencial para garantir que os processos, riscos e conseqüências de privacidade e proteção de dados são totalmente compreendidos. Sua empresa está indo muito bem nessa área. Como lembrete, o processo de habilidades e educação deve incluir, mas não se limitar a: \nNOTA: • Definição de habilidades, níveis e requisitos internos para tarefas e posições relacionadas ao DPP \n NOTA: • Mapeamento de habilidades para cargos e funções organizacionais (matriz) \n • Identificação de níveis de qualificação adequados e qualificações ou certificações formais, conforme necessário para cada parte da matriz \n • Caminhos educacionais para diferentes papéis e funções organizacionais no DPP \n • Reunir fontes, materiais e oportunidades educacionais apropriados oportunidades de orientação ou auto-estudo ",




"Sua empresa possui um processo de treinamento robusto e eficaz. O treinamento é um componente importante da conscientização geral, fornecendo oportunidades contínuas de aprendizado e reforçando as principais mensagens em torno do DPP e dos regulamentos de privacidade e proteção de dados. No mínimo, o processo de treinamento deve abranger: \n • Treinamento básico definido e validado sobre regulamentos de privacidade e proteção de dados, preferencialmente obrigatório para todos os membros da empresa \n • Conceito de treinamento baseado na matriz de habilidades e educação \n • Plano de treinamento, normalmente anualmente, incluindo oportunidades de treinamento interno e externo \n • Preparação de materiais de treinamento, para estudo guiado e auto-estudo \n • Auxílios preparatórios para treinamento de maior qualificação no DPP e regulamentos de privacidade e proteção de dados estabelecidos, incluindo preparação para exames de certificação, etc. \n • Fontes e provedores externos de treinamento definidos para fins específicos, por exemplo, treinamento legal ou DPO ",


"Sua empresa possui uma função DPO bem estabelecida. Como lembrete, no mínimo, o processo de manutenção e execução do DPO deve abranger o seguinte: \n • Estrutura organizacional e posicionamento da função DPO, incluindo o escritório do DPO e seus representantes. pontos de contato em outras partes da empresa \n • Projeto de tarefas e processos administrativos para a função DPO \n • Projeto de programa de trabalho regular em um ciclo anual \n • Planejamento de recursos humanos, habilidades e necessidades educacionais ",


"Sua empresa está indo bem gerenciando o orçamento e os recursos da função DPO. Como lembrete, o processo de orçamento e recursos deve abranger pelo menos: \nCiclo de orçamento financeiro anual, vinculando-se ao orçamento geral \nPlanejamento de recursos humanos e pessoal \nPlanejamento de recursos técnicos , incluindo ferramentas, licenciamento, etc. \nPlanejamento e orçamento de serviços externos, por exemplo, para consultores ou consultores jurídicos \n • Links para relatórios financeiros gerais da empresa ",



"Você tem uma representação excepcional da função DPO na empresa em geral. Como lembrete, o processo de gerenciamento de interfaces organizacionais deve abranger pelo menos: \n • Documentação de contatos regulares e formais em toda a empresa \n • Participação do DPO em comitês permanentes e outras reuniões institucionais formais \n • Comunicações regulares entre a função DPO e outras unidades organizacionais, incluindo atas e outros relatórios \n NOTA: • Etapas do processo documentadas que exigem o envolvimento do DPO, incluindo consulta e informação (RACI) ",



"Os relatórios internos e externos formais são uma parte importante da função DPO. Sua empresa está indo muito bem nessa área. Como um lembrete, no mínimo, o processo de gerenciamento de relatórios deve cobrir: \n • Agendamentos de relatórios para relatórios internos e externos para e pela função DPO \n • Procedimentos que especificam modelos de relatório, conteúdo formal, frequência e distribuição, bem como classificações da CIA para relatórios \n • Procedimento de rastreamento de relatórios, abrangendo todos os cronogramas de relatórios ",


"Sua empresa está bem posicionada para gerenciar conformidade com regulamentos de privacidade e proteção de dados e requisitos relacionados que são contratados por serviços externos. Como lembrete, o processo de gerenciamento de serviços externos deve abordar, no mínimo: \n • Objetivo e substância dos serviços externos , incluindo um contrato de processamento \n • Nível de proteção definido e acordado para os serviços prestados, especificando confidencialidade, integridade e disponibilidade \n • Análise de risco do fornecedor, incluindo verificações detalhadas e due diligence, quando apropriado \n • Análise de segurança da informação \n • Direito de auditar, analisar os resultados da revisão e rastrear as ações corretivas \n NOTA: • Verificação de antecedentes de recursos humanos, quando apropriado e permitido legalmente ",


"Os controles de aquisição de dados da sua empresa são bem mantidos. Como um lembrete, no mínimo, o processo para gerenciar esses controles deve abordar: Identificação de processos organizacionais que podem intencionalmente ou acidentalmente adquirir dados pessoais \n • Documentação de fluxos e dados de entrada de dados interfaces (por exemplo, escritas, web, outras) \n • Identificação da origem dos dados sempre que possível (por exemplo, diretamente do titular dos dados, controlador, processador, outros atores da cadeia de suprimentos, etc.) \n • Documentação dos controles relacionados nos controles internos registro",



"Os controles de processamento da sua empresa são bem mantidos. Como lembrete, o processo de manutenção de tais controles deve abranger: \n • Identificação das etapas do processo, entradas e saídas que devem ser controladas \n • Identificação dos pontos de entrega para terceiros, por exemplo, processadores ou autoridades \n • Definição de objetivos e tipos de controle (por exemplo, preventivo, detetive, corretivo) \n • Documentação dos controles relacionados no registro de controles internos ",


"Os controles de armazenamento da sua empresa são bem mantidos. Como lembrete, o processo de manutenção de tais controles deve abranger pelo menos: \n • Identificação de tipos e locais de armazenamento de dados pessoais, como mapa de armazenamento \n • Análise de instâncias de armazenamento em a arquitetura geral de TI \n • Identificação de instâncias de armazenamento externo, por exemplo, de terceiros, virtualizadas, nuvem \n • Identificação e mapeamento de pontos de transferência entre processos principais (dados em fluxo) e armazenamento (dados em repouso) \n • Documentação de controles relacionados no registro de controles internos ",



"Os controles de exclusão da sua empresa são bem mantidos. Como lembrete, o processo para manter os controles de exclusão deve abranger pelo menos: \n • Identificação dos pontos de exclusão no sistema geral \n • Mapeamento dos controles antes da exclusão \n • Manutenção de um log de exclusão \nMapa dos controles após a exclusão \n • Verificação da remoção do registro de dados pessoais \n • Documentação dos controles relacionados no registro de controles internos ",



"Os controles de monitoramento da sua empresa são bem mantidos. Como um lembrete, o processo para manter os controles de monitoramento deve cobrir pelo menos: \n • Mapeamento do processamento de dados pessoais para o monitoramento geral, incluindo ferramentas \n • Identificação das necessidades de monitoramento no registro do processo \n • Mapeamento das necessidades de relatórios e aplicação aos processos de monitoramento \n • Revisão recorrente da densidade e extensão do monitoramento \n • Documentação dos controles relacionados no registro de controles internos ",


"Sua empresa está bem preparada para gerenciar revisões independentes. Como lembrete, o gerenciamento de revisões independentes requer etapas de planejamento semelhantes às revisões padrão, incluindo notificação, trabalho de campo, análise e relatório. Os profissionais e empresas do DPP podem se beneficiar da alavancagem de processos padronizados de auditoria e revisão para Revisões do DPP. Eles devem ainda vincular-se à estrutura e ao conteúdo mínimos dos relatórios do DPO, conforme estabelecido nos regulamentos estabelecidos de privacidade e proteção de dados. "

];