module.exports = [

"Estrutura de governança Algum esforço adicional seria útil nessa área. Quando apropriado, a estrutura de governança deve fazer referência a políticas e procedimentos existentes vinculados ao processamento de dados pessoais (por exemplo, a política de segurança da informação ou a política de gerenciamento de identidade e acesso). Da mesma forma , os conceitos e disposições organizacionais e técnicos devem ser referenciados para garantir consistência (por exemplo, quaisquer esquemas de classificação de dados existentes ou a determinação dos níveis de proteção de ativos de informações). " ,


"Podem ser necessárias pequenas melhorias no registro de processamento da sua empresa. Os elementos de governança em torno de um registro de processamento incluem, mas não estão limitados a: \n • Recursos de informações usados ​​(do registro de dados pessoais) \n • Finalidade (s) do processamento \n • Processos de negócios ou outros processos organizacionais que utilizam os ativos \n • Ciclo de vida do processamento desde a aquisição inicial de dados até a exclusão de dados (planejado ou ad hoc) O processo de governança em torno do registro de processamento também deve definir uma função ou função responsável pela manutenção do registro. acessibilidade do registro a análises internas e externas. Outras disposições de governança podem incluir o escopo e o procedimento para apresentar o registro como evidência, tanto interna quanto externamente. Em situações em que o processamento complexo de grandes quantidades de dados pessoais ocorre, o registro deve ser regidos por uma política ou procedimento operacional chave apropriado. ",

"Sua empresa pode precisar fazer algumas melhorias nessa área. Uma empresa deve estabelecer, manter, monitorar e adaptar continuamente regras corporativas vinculativas que reflitam de maneira adequada e abrangente a estrutura de governança interna e externa. As atividades em conjunto com as BCRs incluem, mas não estão limitadas a elas. para: \n • Definição, descrição e aprovação de BCRs pela alta administração \n • Comunicação de BCRs em toda a empresa \n • Validação e atualização anual ou ad hoc de BCRs \n • Integração de BCRs em relacionamentos contratuais de terceiros \n • Monitoramento da conformidade do BCR interna e externamente ",


"As regras de consentimento da sua empresa podem precisar de pequenos aprimoramentos. No mínimo, as disposições de governança relacionadas ao consentimento devem abranger: \n • Transparência e permitir informações aos titulares dos dados \n • Tipos de consentimento e requisitos relacionados \n • Retirada do consentimento dos titulares dos dados \n • Processos, controles e verificação específicos para consentimento da criança, incluindo verificação apropriada da idade e / ou autoridade dos pais, bem como consentimento dos pais \n • Canais de comunicação, simplicidade de linguagem e acessibilidade de interfaces baseadas em consentimento ",

"Sua empresa está moderadamente equipada para processar solicitações de titulares de dados. No mínimo, as disposições de governança relacionadas a solicitações de titulares de dados devem abranger: \n • Receber e documentar solicitações de titulares de dados \n • Validação de solicitações relacionadas a objetivos, legal e técnica \n Resposta formal, incluindo canais e formatos de comunicação \n • Interfaces para processos internos e da cadeia de suprimentos \n • Interface para registro de dados pessoais e registro de processamento \n • Revisão independente de solicitações pela função DPO ",


"Adquira, identifique e classifique dados pessoais Algumas áreas a serem aprimoradas \n Sua empresa deve fazer alguns aprimoramentos para lidar melhor com as reclamações dos titulares de dados. No mínimo, as disposições de governança relacionadas às reclamações dos titulares de dados devem cobrir: \n • Recebimento e documentação inicial , incluindo qualquer resposta formal às autoridades de supervisão \n • Análise de reclamações, incluindo interfaces organizacionais, legais e técnicas dentro da empresa \n • Definição e implementação de remediação quando aplicável \n • Identificação de possíveis lacunas ou deficiências que levem à reclamação e oportunidades para melhoria" ,

"Sua empresa deve fazer pequenos ajustes no processo de governança para garantir uma supervisão imparcial. As atividades em conjunto com a supervisão imparcial incluem, mas não estão limitadas a: \n • Funções organizacionais que executam e garantem uma supervisão imparcial \n • Funções e responsabilidades (RACI), incluindo imparcialidade demonstrada \n • Objetivos, escopo e extensão das atividades de supervisão \n • Frequência baseada em risco das atividades de supervisão \n • Procedimentos e orientações para o planejamento, implantação e elaboração de relatórios \n • A aquisição de novos dados pessoais, identificação de dados pessoais existentes Os dados e a classificação dos ativos de informação formam a base para gerenciar e controlar esses dados, de acordo com os regulamentos estabelecidos de privacidade e proteção de dados. Os profissionais e empresas de DPP devem, portanto, fornecer um processo robusto que garanta o processamento conforme a regulamentação de privacidade e proteção de dados, bem como o gerenciamento eficiente de dados. Esse processo também deve estabelecer um ciclo de vida multado e mensurável dos dados pessoais, tendo em conta o princípio da minimização dos dados. ",


"Algum esforço adicional seria útil nessa área. No mínimo, as seguintes partes do ciclo devem ser definidas e implementadas: \n • Criação ou aquisição de dados, incluindo a cadeia de processamento de dados pessoais (fornecimento) \n • Classificação de ativos de informações , incluindo níveis de proteção e atribuição a categorias especiais \n • Inclusão no registro de dados pessoais e no processamento e remoção de registros \n • Processamento real e controles relacionados \n • Armazenamento temporário e permanente, incluindo armazenamento virtualizado e em nuvem \n • Arquivamento e agregação \n • Exclusão, planejada (fim da vida útil ou fim da finalidade) e ad hoc (solicitação de apagamento etc.) ",

"Podem ser necessárias pequenas melhorias no processo da sua empresa para identificar e documentar dados pessoais. O processo de identificação deve, no mínimo, abordar os seguintes aspectos: \n • Definição de critérios de acordo com os regulamentos estabelecidos de privacidade e proteção de dados \n • Procedimento para analisar conjuntos de dados existentes, possivelmente em combinação com a análise dos níveis de proteção de segurança (CIA) \n • Procedimento de entrega para registro de dados pessoais \n • Análise de inferência potencial (identificação indireta de pessoas físicas) de conjuntos de dados separados e / ou dispersos \n • Procedimento de integração para novos dados \n • Procedimentos e controles para terceiros ",


"Sua empresa deve fazer alguns aprimoramentos para manter melhor a classificação dos dados. No mínimo, a classificação dos dados pessoais deve abordar: \n • Atributo geral de pessoal de acordo com os regulamentos estabelecidos de privacidade e proteção de dados; maior relevância pessoal como PII, se necessário \n • Classificação específica relacionada a categorias e finalidades especiais, incluindo limitações e requisitos adicionais de segurança \n • Classificação em termos de não repúdio de transações envolvendo dados pessoais \n • Outros aspectos, como sigilo profissional aplicável ou critérios de acesso restrito ",

"O registro de dados pessoais da sua empresa geralmente é bem mantido. No mínimo, o processo de registro de dados pessoais deve abordar: \n • Tipo de dados e agregação (se houver) em ativos de informações \n • Links relevantes entre conjuntos de dados que formam informações ativos sob regulamentos estabelecidos de privacidade e proteção de dados \n • Tipos e formatos de dados, incluindo dados não mantidos em formatos eletrônicos (por exemplo, papel, microficha) \n • Localização e instanciação de dados, incluindo várias cópias, imagens virtualizadas e em nuvem, etc. \n • Informações sobre o ciclo de vida e o tempo de vida útil, incluindo arquivamento e exclusão planejados \n • Etapas de processamento vinculadas, unidades organizacionais e finalidades de processamento, detalhando claramente quando, por que, onde e por quem do processamento de dados pessoais ",


"Sua empresa está moderadamente bem equipada para gerenciar dados de categorias especiais. Isso requer um processo robusto que identifica, controla e documenta qualquer processamento de dados pertencentes a uma ou mais categorias especiais, cobrindo no mínimo, mas não limitado a: \n • Mapeamento de ativos de informações identificados para categorias especiais de acordo com os regulamentos estabelecidos de privacidade e proteção de dados \n • Documentação de circunstâncias justificativas (conforme os regulamentos estabelecidos de privacidade e proteção de dados) para cada ativo de informações \n • Documentação de qualquer classificação nova ou alterada desses ativos de informação \n • Documentação de todas as comunicações com titulares de dados ou autoridades de supervisão relacionadas ao ativo de informação \n • Documentação de consentimento relacionado a ativos e retirada de consentimento \n • Links verificados para registro de dados pessoais e registro de processamento, incluindo evidências de processamento restrito ao (s) objetivo (s) definido (s) ",

"Sua empresa geralmente está preparada para responder às demandas de apagamento. O processo deve, no mínimo, abordar os seguintes aspectos: \n • Recebimento, confirmação e análise de solicitações de apagamento por titulares de dados ou autoridades competentes \n • Validação e internalização de solicitações de apagamento transferidas por terceiros \n • Interfaces definidas para outros processos, ou seja, registro de dados pessoais e registro de processamento, classificação e ciclo de vida dos dados \n • Aprovações e procedimentos de verificação independente em torno do apagamento \n • Procedimento de confirmação e comunicação de apagamento ( aos titulares ou autoridades de dados) ",




"O processamento de dados pessoais está sujeito a vários riscos predefinidos que devem ser identificados, avaliados e tratados de maneira adequada e apropriada. O impacto potencial desses riscos deve ser avaliado e analisado em vista das medidas existentes de mitigação de riscos. O processo de gerenciamento de riscos deve gerenciar ainda mais o risco residual, usando ferramentas e padrões reconhecidos. Sua empresa pode revisar sua avaliação de riscos. Os resultados da avaliação de riscos devem incluir, no mínimo: \n • Registro abrangente de eventos e ameaças que levam à privacidade e proteção de dados. categorias de risco \n • Estimativas de frequência e premissas de precaução \n • Agregação e agrupamento de eventos que levam aos mesmos riscos que se materializam \n • Classificação de risco, geralmente de acordo com o esquema geral de classificação de risco organizacional ",

"Sua empresa pode revisar seu DPIA quanto a deficiências. O DPIA deve levar em consideração os controles existentes e as medidas de mitigação de risco, e deve identificar o impacto potencial resultante do risco residual que não foi ou não pode ser totalmente mitigado." ,



"Sua empresa está realizando um trabalho adequado para gerenciar o tratamento de riscos. Como lembrete, o processo de tratamento de riscos deve, no mínimo, abranger o seguinte: \n • Evitar ou eliminar riscos, incluindo alterações nos arranjos de processamento ou descontinuação de processamento (reestruturação ou saída) \n • Eliminação de riscos por meio de controles ou salvaguardas adicionais \n • Transferência de riscos, incluindo a reestruturação da cadeia de fornecimento de dados pessoais \n • Redução de riscos por meio de controles adicionais ou medidas de mitigação \n • Tolerância a riscos, com base na frequência e impacto estimados ",

"Sua empresa pode considerar pequenas melhorias no processo de validação de riscos. No mínimo, o processo de validação de riscos deve abordar: \n • Confirmação (ou alteração) dos resultados da avaliação de riscos, incluindo estimativas de frequência e universo de eventos / ameaças \n • Revisão da eficácia das medidas e atividades de tratamento, com base em um período razoável de observação \n • Revisão de quaisquer incidentes ou violações que possam ter ocorrido desde a última validação \n • Análise de quaisquer alterações na estrutura e nos termos de referência, ou seja, , em relação a quaisquer eventos legislativos ou regulamentares, políticos ou financeiros ",



"Sua empresa está fazendo um trabalho moderadamente bom nesta área. O anonimato e a pseudonimização devem abranger, mas não estão limitados a: \n • Identificação de conjuntos de dados pessoais a serem anonimizados / pseudonimizados \n • Definição de técnicas em todos os níveis técnicos, por exemplo, arquivo, registro de banco de dados, sistemas de arquivos não eletrônicos \n • Documentação e registro real de anonimização / pseudonimização \n • Link definido para registro de dados pessoais e registro de processamento \n • Aplicação recursiva do princípio da necessidade de conhecimento em toda a cadeia de suprimentos; da necessidade real de conhecer o gerenciamento de identidades e acessos ",

"A estratégia de criptografia e seus componentes devem se basear em risco e eficiência, garantindo que os riscos de privacidade e proteção de dados sejam totalmente compreendidos e internalizados em qualquer decisão. Sua empresa geralmente está se saindo bem nessa área. Como lembrete, no mínimo, o processo de criptografia deve abordar: \n • Conjunto definitivo de dados pessoais e ativos de informações a serem criptografados, com base nos níveis de proteção atribuídos e nos riscos e impactos de privacidade e proteção de dados \n • Definição de técnicas e objetivos de criptografia, por exemplo, dados individuais, elementos de banco de dados, bancos de dados inteiros, transações etc. \n • Links para técnicas e ferramentas de criptografia reconhecidas ou aprovadas, já em uso na empresa \n • Escopo, planejamento e etapas de implementação para criptografia adicional necessária para dados pessoais ",


"Sua empresa pode fazer pequenos aprimoramentos para gerenciar melhor os níveis de proteção. O processo em torno dos níveis de proteção de dados pessoais fornece uma interface definida (nos dois sentidos) entre a segurança geral das informações e a segurança dos dados pessoais. Os profissionais e empresas do DPP devem refletir isso definindo as interfaces organizacionais apropriadas apoiar o fluxo de informações e a representação adequada de dados pessoais nas análises do nível de proteção. " ,

"Sua empresa está moderadamente preparada para gerenciar a resiliência. No mínimo, o processo de resiliência deve abranger: \n • Criticidade de dados pessoais, geralmente expressa como uma combinação de requisitos de integridade e disponibilidade \n • Processamento de criticidade em função do tempo, ou seja, período máximo de indisponibilidade tolerável, perda máxima de dados tolerável \n • Planos de recuperação para conjuntos de dados pessoais \n • Links definidos para continuidade geral de negócios e planos de continuidade de serviços de TI \n • Conceitos de backup e restauração para conjuntos de dados pessoais, vinculados a backup e restaurar planos e procedimentos \n • Múltipla instanciação de conjuntos de dados pessoais que exigem alta disponibilidade, ou seja, processamento totalmente resiliente ",

"Sua empresa está gerenciando de maneira um tanto eficaz o acesso a dados pessoais. As restrições e limitações de acesso resultantes de requisitos de processamento de dados pessoais devem ser documentadas e alimentadas no processo geral do IAM. O processo de gerenciamento de acesso a dados pessoais fornece, portanto, uma interface (nos dois sentidos) para IAM. Os profissionais e empresas de DPP devem refletir isso definindo interfaces organizacionais apropriadas para apoiar o fluxo de informações e a representação adequada de dados pessoais no gerenciamento de acesso. ",


"Sua empresa geralmente possui um bom processo para gerenciar testes e avaliação da segurança de dados pessoais. Como lembrete, no mínimo, o processo deve abordar: \n • Tipos de teste e avaliação, por exemplo, teste conceitual, teste de vulnerabilidade e verificação de vulnerabilidades. testes de penetração \n • Frequência dos testes \n • Evidências de melhoria contínua, isto é, testes e avaliações progressivamente mais exigentes ao longo do tempo \n • Registro de testes e obtenção de evidências \n • Análise de deficiências e documentação de oportunidades de melhoria ",



"Sua empresa possui um processo geralmente adequado para gerenciar controladores e processadores. Como lembrete, o processo deve abranger pelo menos: \n • Identificação de controladores primários e conjuntos, incluindo objetivos individuais ou coletivos para o processamento de dados pessoais \n • Identificação de processadores, incluindo o escopo definido e a extensão do processamento em nome de um ou mais controladores \n • Links para o registro de dados pessoais, refletindo os conjuntos de dados e a maneira como eles são tratados na cadeia de suprimentos (dados em fluxo; dados em repouso) \n • Links para o registro de processamento, refletindo os processos ou etapas do processo executados por cada ator na cadeia de suprimentos \n • Documentação dos acordos de gerenciamento e controle de fornecedores (processadores), geralmente incorporados ao gerenciamento geral de fornecedores de uma empresa ",

"Em cadeias de suprimentos complexas, o processo de gerenciamento de subprocessamento é um elemento essencial para garantir a conformidade da regulamentação de privacidade e proteção de dados em toda a cadeia de suprimentos. Sua empresa está se saindo bem nessa área. Como lembrete, o processo de gerenciamento de subprocessos deve cobrir, em no mínimo: \n • Procedimento formal de solicitação para processadores primários; divulgação de qualquer terceirização adicional \n • Documentação e registro de subprocessamento, incluindo escopo, extensão e objetivo (s) \n • Evidências de conformidade com os regulamentos de privacidade e proteção de dados às normas esperadas , incluindo processos, controles, conceitos e resultados da revisão \n • Relatórios de auditoria e outras garantias independentes, se disponíveis \n • Processamento de contratos entre processadores primários e subprocessadores ",


"Enquanto sua empresa está se saindo bem nessa área, pequenas melhorias podem aumentar a eficácia do processo. No mínimo, o processo em torno desses contratos deve abranger: \n • Definição, aprovação e implementação de acordos padronizados, incluindo modelos \n • Monitoramento regular do cumprimento \n • Planejamento e execução de revisões, principalmente sob o direito padrão de auditoria \n • Recebimento, análise e validação de evidências de terceiros para processamento conforme, por exemplo, relatórios de certificação e atestado \n • Regular revisão e atualização de acordos de processamento, termos e condições, de acordo com a atividade legislativa e reguladora \n • Planejamento de término e saída para relacionamentos contratuais individuais ",

"Sua empresa está um pouco preparada nessa área. Em uma cadeia de suprimentos com vários atores, os impactos resultantes dos riscos à privacidade e à proteção de dados podem se materializar a qualquer momento e a qualquer momento. Portanto, os profissionais e empresas de DPP devem aplicar sua própria abordagem de DPIA a todos os partes da cadeia de suprimentos e documentar o feedback recebido de cada uma das partes, incluindo relatórios padronizados, revisões ad hoc ou verificações de plausibilidade.O impacto geral deve ser agregado, com base no registro de processamento e no fluxo de dados em vários participantes da cadeia de suprimentos. Deve-se tomar cuidado para entender como os impactos em um local podem agravar os impactos em outras partes da cadeia de suprimentos." ,


"Onde o processamento de dados pessoais é realizado em uma cadeia de suprimentos, os controles internos de um processador ou subprocessador devem ser tão eficazes quanto os da organização controladora. O processo de controles da cadeia de suprimentos da sua empresa é essencial para garantir que este seja o caso. , o processo deve abranger o seguinte: \n • Obtenção e análise de documentação de controles internos de terceiros \n • Mapeamento para o sistema de controle interno (ICS) na organização do controlador \n • Procedimentos para teste de projeto (ToD), isto é, padrão técnicas para avaliar controles \n • Procedimentos para teste de eficácia (ToE), isto é, amostragem e coleta de evidências que demonstram a eficácia dos controles de terceiros \n • Arranjos de monitoramento e revisão de logs, incluindo acessibilidade dos dados de log, desde que relacionados a processamento de dados pessoais \n • Direitos de auditoria pontuais ou contínuos, incluindo planejamento e implantação de auditoria ",



"Onde o processamento de dados pessoais é realizado em uma cadeia de suprimentos, os controles internos de um processador ou subprocessador devem ser tão eficazes quanto os da organização controladora. O processo de controles da cadeia de suprimentos da sua empresa é essencial para garantir que este seja o caso. , o processo deve abranger o seguinte: \n • Obtenção e análise de documentação de controles internos de terceiros \n • Mapeamento para o sistema de controle interno (ICS) na organização do controlador \n • Procedimentos para teste de projeto (ToD), isto é, padrão técnicas para avaliar controles \n • Procedimentos para teste de eficácia (ToE), isto é, amostragem e coleta de evidências que demonstram a eficácia dos controles de terceiros \n • Arranjos de monitoramento e revisão de logs, incluindo acessibilidade dos dados de log, desde que relacionados a processamento de dados pessoais \n • Direitos de auditoria pontuais ou contínuos, incluindo planejamento e implantação de auditoria ",

"Sua empresa geralmente está equipada para notificar os titulares dos dados em caso de incidente ou violação. Como um lembrete, no mínimo, o processo de notificação dos titulares dos dados deve cobrir: \n • Formato e modelos de relatório padronizados, adaptados e otimizados para vários canais de comunicação (individual, grupo, público) \n • Mensagens-chave predefinidas e aprovadas que expressam as ações da empresa (investigação, conseqüências, remediação, melhoria etc.) \n • Responsabilidades organizacionais em relação à formulação e transmissão de chaves mensagens, por exemplo, envolvimento do departamento de comunicações, aconselhamento jurídico, etc. \n • Facilidades de comunicação ad hoc oferecidas aos titulares dos dados, por exemplo, linha de ajuda, número de telefone gratuito, local escuro, etc. " ,


"O processo de gerenciamento de incidentes e crises da sua empresa geralmente é adequado. Da perspectiva dos profissionais de DPP e das unidades organizacionais que descobriram inicialmente a violação, o processo deve abranger pelo menos: \n • Descrição e documentação de fatos e números conhecidos, em um formato padronizado, onde apropriado \n • Link definido para o processo geral de escalação e alerta, geralmente definido pela função de gerenciamento de crises nos negócios (BCM) \n • Cenário de dados pessoais genéricos predefinidos para continuidade dos negócios e gerenciamento de crises, semelhante a outros cenários especiais, como ataque cibernético, pandemia, etc. \n • Relacionamentos e canais de comunicação predefinidos com atores externos, ou seja, serviços externos, como especialistas em investigação ou forenses \n • Protocolo de comunicação contínuo entre unidades de linha organizacional e equipes de gerenciamento de incidentes / crises ",

"Sua empresa está preparada adequadamente para gerenciar evidências e reivindicações de forma adequada. As violações de dados pessoais representam casos de não conformidade, mas também indicam que negligência ou atividade criminosa interna e / ou externa pode estar presente. O processo de evidências e reivindicações deve, portanto, cobrir, no mínimo : \n • Procedimentos definidos para coleta e proteção de evidências, incluindo cadeia de custódia \n • Disponibilidade de serviços especializados, como forense de TI \n • Procedimento e modelos para análise e relatório pós-incidente \n • Procedimento para fundamentar reivindicações contra terceiros, incluindo a base legal ou contratual para tais reclamações \n • Procedimento para preparar defesas contra reclamações de terceiros, incluindo aspectos de apelação (decisões regulatórias) \n • Link definido para relatar DPO incidente ",


"Sua empresa está mantendo adequadamente a conscientização da empresa. No mínimo, o processo de conscientização em toda a empresa deve abranger: \n • Definição e descrição dos requisitos de privacidade e proteção de dados nos processos organizacionais diários, incluindo exemplos de processamento de dados pessoais \n • Materiais de campanha enfatizando aspectos específicos do DPP, processamento de dados pessoais e pontos de privacidade e proteção de dados a serem observados \n • Planos de programas / projetos que estabelecem datas de metas para medidas de conscientização \n • Materiais de conscientização de terceiros e detalhes sobre como incluir terceiros na conscientização campanhas ",


"A proteção de dados e o gerenciamento de privacidade, incluindo o contexto de regulamentos estabelecidos de privacidade e proteção de dados, exigem um conjunto de habilidades e qualificações que devem estar presentes na empresa ou contratadas por meio de serviços externos. O gerenciamento de habilidades e educação é um processo essencial para garantir que os riscos de privacidade e proteção de dados e suas conseqüências são totalmente compreendidos. Sua empresa está se saindo bem nessa área. Como lembrete, o processo de habilidades e educação deve incluir, mas não se limitar a: \n • Definição de habilidades, níveis e requisitos internos para tarefas e posições relacionadas ao DPP \n • Mapeamento de habilidades para cargos e funções organizacionais (matriz) \n • Identificação de níveis de qualificação adequados e qualificações ou certificações formais, conforme necessário para cada parte da matriz \n • Caminhos da educação para diferentes funções e funções organizacionais no DPP \n • Reunir fontes, materiais e oportunidades educacionais apropriados organizações para orientação ou auto-estudo ",

"Pequenas modificações podem melhorar a eficácia do processo de treinamento da sua empresa. O treinamento é um componente importante da conscientização geral, fornecendo oportunidades de aprendizado contínuo e reforçando as principais mensagens sobre o DPP e os requisitos de privacidade e proteção de dados. No mínimo, o processo de treinamento deve abranger: \n • Treinamento básico definido e validado sobre regulamentos de privacidade e proteção de dados, preferencialmente obrigatório para todos os membros da empresa \n • Conceito de treinamento baseado na matriz de habilidades e educação \n • Plano de treinamento, geralmente anualmente, incluindo interno e externo oportunidades de treinamento \n • Preparação de materiais de treinamento para estudo guiado e auto-estudo \n • Auxílios preparatórios para treinamento de qualificações mais altas no DPP e regulamentos de privacidade e proteção de dados estabelecidos, incluindo preparação para exames de certificação, etc. \n • Fontes de treinamento externas definidas e provedores para fins específicos, por exemplo, treinamento legal ou DPO ",



"Sua empresa pode precisar de leves aprimoramentos na função DPO. Como lembrete, no mínimo, o processo de manutenção e execução do DPO deve abranger o seguinte: \n • Estrutura organizacional e posicionamento da função DPO, incluindo o escritório do DPO e seus pontos de contato em outras partes da empresa \n • Projeto de tarefas e processos administrativos para a função DPO \n • Projeto de programa de trabalho regular em um ciclo anual \n • Planejamento de recursos humanos, habilidades e necessidades educacionais ",

"Sua empresa está fazendo um trabalho adequado gerenciando o orçamento e os recursos da função DPO. Como lembrete, o processo de orçamento e recursos deve abranger pelo menos: \n • Ciclo anual do orçamento financeiro, vinculando-se ao orçamento geral \n • Recursos humanos e planejamento de funcionários \n • Planejamento de recursos técnicos, incluindo ferramentas, licenciamento, etc. \n • Planejamento e orçamento de serviços externos, por exemplo, para consultores ou consultores jurídicos \n • Links para relatórios financeiros gerais da empresa ",


"Sua função DPO geralmente está bem representada na empresa em geral. Como lembrete, o processo de gerenciamento de interfaces organizacionais deve abranger pelo menos: \n • Documentação de contatos regulares e formais em toda a empresa \n • Participação do DPO em comitês permanentes e outras reuniões institucionais formais \n • Comunicações regulares entre a função DPO e outras unidades organizacionais, incluindo atas e outros relatórios \n • Etapas do processo documentadas que requerem envolvimento do DPO, incluindo consulta e informação (RACI) ",

"Os relatórios internos e externos formais são uma parte importante da função DPO. Sua empresa está se saindo bem nesta área. Como lembrete, no mínimo, o processo de gerenciamento de relatórios deve cobrir: \n • Agendamentos de relatórios para relatórios internos e externos para e pela função DPO \n • Agendamentos de relatórios para relatórios de autoridade de supervisão \n • Procedimentos que especificam modelos de relatórios, conteúdo formal, frequência e distribuição, bem como classificações da CIA para relatórios \n • Procedimento de rastreamento para relatórios, abrangendo todos os agendamentos de relatórios ",


"Sua empresa está posicionada adequadamente para gerenciar a conformidade da regulamentação de privacidade e proteção de dados e os requisitos relacionados que são contratados por serviços externos. Como lembrete, o processo de gerenciamento de serviços externos deve abordar, no mínimo: \n • Finalidade e substância dos serviços externos , incluindo um contrato de processamento \n • Nível de proteção definido e acordado para os serviços prestados, especificando confidencialidade, integridade e disponibilidade \n • Análise de risco do fornecedor, incluindo verificações detalhadas e due diligence, quando apropriado \n • Análise de segurança da informação \n • Direito de auditoria, análise dos resultados da revisão e rastreamento de ações corretivas \n • Verificação de antecedentes de recursos humanos, quando apropriado e permitido por lei ",



"Os controles de aquisição de dados da sua empresa são um pouco bem mantidos. Como um lembrete, no mínimo, o processo para gerenciar esses controles deve abordar: \n • Identificação de processos organizacionais que podem intencionalmente ou acidentalmente adquirir dados pessoais \n • Documentação de entrada fluxos de dados e interfaces de dados (por exemplo, escritos, web, outros) \n • Identificação da origem dos dados sempre que possível (por exemplo, direto do titular, controlador, processador, outros atores da cadeia de suprimentos, etc.) \n • Documentação dos controles relacionados no registro de controles internos ",

"Os controles de processamento da sua empresa são um pouco bem mantidos. Como lembrete, o processo de manutenção de tais controles deve abranger: \n • Identificação das etapas do processo, entradas e saídas que devem ser controladas \n • Identificação dos pontos de entrega para terceiros , por exemplo, processadores ou autoridades \n • Definição de objetivos e tipos de controle (por exemplo, preventivo, detetive, corretivo) \n • Documentação dos controles relacionados no registro de controles internos ",


"Os controles de armazenamento da sua empresa são um pouco bem mantidos. Como lembrete, o processo de manutenção de tais controles deve abranger pelo menos: \n • Identificação de tipos e locais de armazenamento de dados pessoais, como mapa de armazenamento \n • Análise de instâncias de armazenamento dentro da arquitetura geral de TI \n • Identificação de instâncias de armazenamento externo, por exemplo, de terceiros, virtualizadas, nuvem \n • Identificação e mapeamento de pontos de transferência entre processos principais (dados em fluxo) e armazenamento (dados em repouso) \n • Documentação controles relacionados no registro de controles internos ",

"Os controles de exclusão da sua empresa são um pouco bem mantidos. Como lembrete, o processo para manter os controles de exclusão deve cobrir pelo menos: \n • Identificação dos pontos de exclusão no sistema geral \n • Mapeamento dos controles antes da exclusão \n • Manutenção um registro de exclusão \n • Mapeamento de controles após exclusão \n • Verificação de remoção do registro de dados pessoais \n • Documentação de controles relacionados no registro de controles internos ",

"Mantenha os controles de monitoramento \n Os controles de monitoramento da sua empresa são bem mantidos. Como lembrete, o processo para manter os controles de monitoramento deve abranger pelo menos: \n • Mapeamento do processamento de dados pessoais para o monitoramento geral, incluindo ferramentas \n • Identificação de necessidades de monitoramento no registro do processo \n • Mapeamento das necessidades de relatórios e aplicação nos processos de monitoramento \n • Revisão recorrente da densidade e extensão do monitoramento \n • Documentação dos controles relacionados no registro de controles internos ",


"Sua empresa geralmente está preparada para gerenciar revisões independentes. Como lembrete, o gerenciamento de revisões independentes requer etapas de planejamento semelhantes às revisões padrão, incluindo notificação, trabalho de campo, análise e relatório. Os profissionais e empresas do DPP podem se beneficiar da alavancagem de processos padronizados de auditoria e revisão para Revisões do DPP. Além disso, devem vincular-se à estrutura e ao conteúdo mínimos dos relatórios do DPO, conforme estabelecido nas normas ou regulamentos estabelecidos de privacidade e proteção de dados. "

];