module.exports = [


"É necessário grande esforço nesta área. Onde apropriado, a estrutura de governança deve fazer referência a políticas e procedimentos existentes vinculados ao processamento de dados pessoais (por exemplo, a política de segurança da informação ou a política de gerenciamento de identidade e acesso). Da mesma forma, organizacional e técnica os conceitos e disposições devem ser referenciados para garantir a consistência (por exemplo, quaisquer esquemas de classificação de dados existentes ou a determinação dos níveis de proteção de ativos de informação). ",

"São necessárias melhorias significativas no registro de processamento da sua empresa. Os elementos de governança em torno de um registro de processamento incluem, entre outros: Ativos de informações utilizados (do registro de dados pessoais) Objetivo (s) de processamento Processos de negócios ou outros processos organizacionais que utilizam os ativos ciclo de vida desde a aquisição inicial dos dados até a exclusão dos dados (planejado ou ad hoc) O processo de governança em torno do registro de processamento deve definir ainda mais uma função ou função responsável pela manutenção do registro, bem como a acessibilidade do registro a análises internas e externas. as disposições podem incluir o escopo e o procedimento para apresentar o registro como evidência, tanto interna quanto externamente. Nas situações em que ocorre um processamento complexo de grandes quantidades de dados pessoais, o registro deve ser regido por uma política ou procedimento operacional chave apropriado. ",

"Sua empresa precisa prestar muita atenção às melhorias nessa área. Uma empresa deve estabelecer, manter, monitorar e adaptar continuamente regras corporativas vinculativas que reflitam de maneira adequada e abrangente a estrutura de governança interna e externa. As atividades em conjunto com os BCRs incluem, mas não são, limitado a: Definição, descrição e aprovação de BCRs pela alta administração Comunicação de BCRs em toda a empresa Validação e atualização anual ou ad hoc de BCRs Integração de BCRs em relacionamentos contratuais de terceiros Monitoramento da conformidade do BCR interna e externamente ",

"As regras de consentimento da sua empresa estão ausentes. No mínimo, as disposições de governança relacionadas ao consentimento devem abranger: \n • Transparência e permitir informações aos titulares dos dados \n • Tipos de consentimento e requisitos relacionados \n • Retirada do consentimento dos titulares dos dados \n • Processos, controles e verificações específicas para consentimento da criança, incluindo verificação apropriada da idade e / ou autoridade dos pais, bem como consentimento dos pais \n • Canais de comunicação, simplicidade de linguagem e acessibilidade de interfaces baseadas em consentimento ",

"Sua empresa não está preparada para processar solicitações de titulares de dados. No mínimo, as disposições de governança em relação às solicitações de titulares de dados devem abranger: \n • Receber e documentar solicitações de titulares de dados \n • Validação de solicitações relacionadas a objetivos, legal e técnica \n • Resposta formal, incluindo canais e formatos de comunicação \n • Interfaces para processos internos e da cadeia de suprimentos \n • Interface para registro de dados pessoais e registro de processamento \n • Revisão independente de solicitações pela função DPO ",

"Sua empresa não está preparada para lidar com as reclamações dos titulares de dados. No mínimo, as disposições de governança relacionadas às reclamações dos titulares de dados devem abranger: \n • Recebimento e documentação inicial, incluindo qualquer resposta formal às autoridades de supervisão \n • Análise de reclamações, incluindo organizações , interfaces legais e técnicas dentro da empresa \n • Definição e implementação de remediação, quando aplicável \n • Identificação de possíveis lacunas ou deficiências que levem à reclamação e oportunidades de melhoria ",


"É crucial para sua empresa estabelecer um processo para garantir a supervisão objetiva. As atividades em conjunto com a supervisão imparcial incluem, mas não se limitam a: \n • Funções organizacionais que executam e garantem supervisão imparcial \n • Funções e responsabilidades (RACI), incluindo imparcialidade demonstrada \n • Objetivos, escopo e extensão das atividades de supervisão \n • Frequência das atividades de supervisão baseada em risco Procedimentos e orientações para o planejamento, implantação e elaboração de relatórios ",

"É necessário grande esforço nesta área. No mínimo, as seguintes partes do ciclo devem ser definidas e implementadas: \n • Criação ou aquisição de dados, incluindo a cadeia de processamento de dados pessoais (suprimento) \n • Classificação de ativos de informações, incluindo níveis de proteção e atribuição a categorias especiais \n • Inclusão no registro de dados pessoais e no registro e remoção de processamento \n • Processamento real e controles relacionados \n • Armazenamento temporário e permanente, incluindo armazenamento virtualizado e em nuvem Exclusão de arquivamento e agregação, planejados (fim da vida útil ou fim da finalidade) e ad hoc (solicitação de apagamento etc.) ",

"São necessárias melhorias significativas no processo da sua empresa para identificar e documentar dados pessoais. O processo de identificação deve, no mínimo, abordar os seguintes aspectos: \n • Definição de critérios de acordo com os regulamentos ou normas de privacidade e proteção de dados estabelecidos \n • Procedimento para analisar conjuntos de dados existentes, possivelmente em combinação com a análise dos níveis de proteção de segurança (CIA) \n • Procedimento de entrega para registro de dados pessoais \n • Análise de inferência potencial (identificação indireta de pessoas físicas) a partir de dados separados e / ou dispersos \n • Procedimento de integração para novos dados \n • Procedimentos e controles para terceiros ",


"Sua empresa não está equipada para manter a classificação de dados. No mínimo, a classificação de dados pessoais deve abordar: \n • Atributo geral de 'pessoal' de acordo com os regulamentos ou normas estabelecidas de privacidade e proteção de dados; maior relevância pessoal como PII, se necessário \n • Classificação específica relacionada a categorias e finalidades especiais, incluindo limitações e requisitos adicionais de segurança \n • Classificação em termos de não repúdio de transações envolvendo dados pessoais \n • Outros aspectos, como sigilo profissional aplicável ou critérios de acesso restrito ",

"O registro de dados pessoais da sua empresa precisa de melhorias significativas. No mínimo, o processo de registro de dados pessoais deve abordar: \n • Tipo de dados e agregação (se houver) em ativos de informações \n • Links relevantes entre conjuntos de dados que formam ativos de informações em regulamentos ou normas de privacidade e proteção de dados estabelecidos \n • Tipos e formatos de dados, incluindo dados não mantidos em formatos eletrônicos (por exemplo, papel, microficha) \n • Localização e instanciação de dados, incluindo várias cópias, imagens virtualizadas e em nuvem, etc. \n • Informações sobre o ciclo de vida e o tempo de vida útil, incluindo arquivamento e exclusão planejados \n • Etapas de processamento vinculadas, unidades organizacionais e finalidades de processamento, detalhando claramente quando, por que, onde e por quem do processamento de dados pessoais ",


"Sua empresa não está equipada para gerenciar dados de categorias especiais. Isso requer um processo robusto que identifica, controla e documenta qualquer processamento de dados pertencentes a uma ou mais categorias especiais, cobrindo no mínimo, mas não limitado a: \n • Mapeamento de ativos de informação identificados para categorias especiais de acordo com os regulamentos ou normas estabelecidos de privacidade e proteção de dados \n • Documentação de circunstâncias justificativas (conforme os regulamentos ou normas de privacidade e proteção de dados estabelecidos) para cada ativo de informação \n • Documentação de qualquer classificação nova ou alterada desses ativos de informação \n • Documentação de todas as comunicações com os titulares de dados ou autoridades de supervisão relacionadas ao ativo de informação \n • Documentação do consentimento relacionado ao ativo e retirada do consentimento \n • Links verificados para o registro de dados pessoais e registro de processamento, incluindo evidência de processamento restrito ao (s) objetivo (s) definido (s) ",

"Sua empresa não está preparada para responder às demandas de apagamento. O processo deve, no mínimo, abordar os seguintes aspectos: \n • Recebimento, confirmação e análise de solicitações de apagamento por titulares de dados ou autoridades competentes \n • Validação e internalização de solicitações de apagamento transferidas por terceiros \n • Interfaces definidas para outros processos, isto é, registro de dados pessoais e \n • registro de processamento, classificação e ciclo de vida dos dados \n • Aprovações e procedimentos de verificação independente em torno do apagamento \n • Confirmação e exclusão de apagamento procedimento de comunicação (para titulares ou autoridades de dados) ",


"Sua empresa deve realizar uma avaliação de risco completa. Os resultados da avaliação de risco devem incluir, no mínimo: \n • Registro abrangente de eventos e ameaças que levem a categorias de risco de privacidade e proteção de dados \n • Estimativas de frequência e premissas de precaução \n • Agregação e agrupamento de eventos que levam aos mesmos riscos que se materializam \n • Classificação de riscos, geralmente de acordo com o esquema abrangente de classificação de riscos organizacionais ",

"Sua empresa deve realizar uma avaliação completa do impacto na proteção de dados. A DPIA deve levar em conta os controles existentes e as medidas de mitigação de riscos, e deve identificar o impacto potencial resultante do risco residual que não foi ou não pode ser totalmente mitigado." ,

"Sua empresa precisa fazer grandes melhorias para gerenciar melhor o tratamento de riscos. O processo de tratamento de riscos deve, no mínimo, abranger o seguinte: \n • Evitar ou eliminar riscos, incluindo alterações nos arranjos de processamento ou interrupção do processamento (reestruturação ou saída) \n • Eliminação de riscos por meio de controles ou salvaguardas adicionais \n • Transferência de riscos, incluindo a reestruturação da cadeia de fornecimento de dados pessoais \n • Redução de riscos por meio de controles adicionais ou medidas de mitigação \n • Tolerância a riscos, com base na frequência e impacto estimados ",

"Sua empresa precisa estabelecer um processo de validação de riscos. No mínimo, esse processo deve abordar: \n • Confirmação (ou alteração) dos resultados da avaliação de riscos, incluindo estimativas de frequência e o universo de eventos / ameaças \n • Revisão da eficácia do tratamento medidas e atividades, com base em um período razoável de observação \n • Revisão de quaisquer incidentes ou violações que possam ter ocorrido desde a última validação \n • Análise de quaisquer alterações na estrutura e nos termos de referência, ou seja, em relação a qualquer legislação eventos regulatórios, políticos ou financeiros ",


"Sua empresa precisa de melhorias nessa área. O anonimato e o pseudonimização devem abranger, mas não estão limitados a: \n • Identificação de conjuntos de dados pessoais a serem anonimizados / pseudonimizados \n • Definição de técnicas em todos os níveis técnicos, por exemplo, arquivo, banco de dados registro, \n • sistemas de arquivo não eletrônicos \n • Documentação e registro de anonimização / pseudonimização real \n • Link definido para registro de dados pessoais e registro de processamento \n • Aplicação recursiva do princípio da necessidade de conhecimento em toda a cadeia de suprimentos; da necessidade real de conhecer o gerenciamento de identidades e acessos ",

"A estratégia de criptografia e seus componentes devem se basear em risco e eficiência, garantindo que os riscos de privacidade e proteção de dados sejam totalmente compreendidos e internalizados em qualquer decisão. Sua empresa precisa de sérias melhorias nessa área. No mínimo, o processo de criptografia deve abordar : \n • Conjunto definitivo de dados pessoais e ativos de informação a serem criptografados, com base nos níveis de proteção atribuídos e nos riscos e impactos de privacidade e proteção de dados \n • Definição de técnicas e objetivos de criptografia, por exemplo, dados individuais, elementos do banco de dados, todo bancos de dados, transações etc. \n • Links para técnicas e ferramentas de criptografia reconhecidas ou aprovadas, já em uso na empresa \n • Escopo, planejamento e etapas de implementação para criptografia adicional necessária para dados pessoais ",


"Sua empresa exige grandes aprimoramentos para gerenciar os níveis de proteção. O processo em torno dos níveis de proteção de dados pessoais fornece uma interface definida (nos dois sentidos) entre a segurança geral das informações e a segurança dos dados pessoais. Os profissionais e empresas do DPP devem refletir isso definindo as interfaces organizacionais apropriadas. apoiar o fluxo de informações e a representação adequada de dados pessoais nas análises do nível de proteção ." ,


"Sua empresa não possui um processo maduro para gerenciar a resiliência. No mínimo, o processo de resiliência deve abranger: \n • Criticidade de dados pessoais, geralmente expressa como uma combinação de requisitos de integridade e disponibilidade \n • Processamento de criticidade em função do tempo , ou seja, período máximo tolerável de indisponibilidade, perda máxima tolerável de dados \n • Planos de recuperação para conjuntos de dados pessoais \n • Links definidos para continuidade geral dos negócios e planos de continuidade de serviço de TI \n • Conceitos de backup e restauração de conjuntos de dados pessoais, vinculados a planos e procedimentos gerais de backup e restauração \n • Múltipla instanciação de conjuntos de dados pessoais que exigem alta disponibilidade, ou seja, processamento totalmente resiliente ",

"Sua empresa não está gerenciando efetivamente o acesso a dados pessoais. As restrições e limitações de acesso resultantes dos requisitos de processamento de dados pessoais devem ser documentadas e alimentadas no processo geral do IAM. O processo de gerenciamento de acesso a dados pessoais fornece, portanto, uma interface (nos dois sentidos) para IAM. Os profissionais e empresas de DPP devem refletir isso definindo interfaces organizacionais apropriadas para apoiar o fluxo de informações e a representação adequada de dados pessoais no gerenciamento de acesso. " ,

"O processo da sua empresa para gerenciar testes e avaliações de segurança de dados pessoais precisa de uma análise séria. No mínimo, o processo deve abordar: \n • Tipos de testes e avaliações, por exemplo, testes conceituais, verificação de vulnerabilidades e testes de penetração \n • Frequência \n • Evidência de melhoria contínua, isto é, testes e avaliações progressivamente mais exigentes ao longo do tempo \n • Registro de log e proteção de evidências \n • Análise de pontos fracos e documentação de oportunidades de melhoria ",

"O processo da sua empresa para gerenciar controladores e processadores precisa de muita atenção. O processo deve cobrir pelo menos: \n • Identificação de controladores primários e conjuntos, incluindo fins individuais ou coletivos para o processamento de dados pessoais \n • Identificação de processadores, incluindo o escopo definido e a extensão do processamento em nome de um ou mais controladores \n • Links para o registro de dados pessoais, refletindo os conjuntos de dados e a maneira como eles são tratados na cadeia de suprimentos (dados em fluxo; dados em repouso) \n • Links para o registro de processamento, refletindo os processos ou etapas do processo executados por cada ator na cadeia de suprimentos \n • Documentação das disposições de gerenciamento e controle de fornecedores (processadores), geralmente incorporadas ao gerenciamento geral de fornecedores de uma empresa ",


"Em cadeias de suprimentos complexas, o processo de gerenciamento de subprocessamento é um elemento essencial para garantir conformidade com regulamentos ou normas de proteção de dados e privacidade estabelecidos em toda a cadeia de suprimentos. Sua empresa precisa de grandes melhorias nessa área. O processo de gerenciamento de subprocessos deve cobrir, no mínimo, : \n • Procedimento formal de solicitação para processadores primários; divulgação de qualquer terceirização adicional \n • Documentação e registro de subprocessamento, incluindo escopo, extensão e objetivo (s) \n • Evidências de regulamentos estabelecidos de privacidade e proteção de dados ou conformidade com normas, incluindo processos, controles, conceitos e resultados da revisão \n • Relatórios de auditoria e outras garantias independentes, se disponíveis \n • Processamento de contratos entre processadores primários e subprocessadores ",

"Os contratos de processamento da sua empresa precisam de um trabalho sério. No mínimo, o processo em torno desses contratos deve abranger: \n • Definição, aprovação e implementação de acordos padronizados, incluindo modelos \n • Monitoramento do cumprimento regularmente \n • Planejamento e execução de revisões, principalmente sob o direito padrão de auditoria \n • Recebimento, análise e validação de evidências de terceiros para processamento conforme, por exemplo, relatórios de certificação e atestado \n • Revisão e atualização regulares de contratos, termos e condições de processamento , de acordo com a atividade legislativa e reguladora \n • Planejamento de término e saída para relações contratuais individuais ",

"Sua empresa tem sérios problemas que precisam ser resolvidos para gerenciar o impacto da cadeia de suprimentos. Em uma cadeia de suprimentos com vários atores, os impactos resultantes dos riscos à privacidade e à proteção de dados podem se materializar a qualquer momento e a qualquer momento. Portanto, os profissionais de DPP e as empresas devem aplicar sua própria abordagem de DPIA em todas as partes da cadeia de suprimentos e documentar o feedback recebido de cada uma das partes, incluindo relatórios padronizados, revisões ad hoc ou verificações de plausibilidade. O impacto geral deve ser agregado, com base no registro de processamento e fluxo de dados entre vários participantes da cadeia de suprimentos. Deve-se tomar cuidado para entender como os impactos em um local podem agravar os impactos em outras partes da cadeia de suprimentos. " ,

"Onde o processamento de dados pessoais é realizado em uma cadeia de suprimentos, os controles internos de um processador ou subprocessador devem ser tão eficazes quanto os da organização controladora. Sua empresa deve fazer grandes aprimoramentos no processo de controles da cadeia de suprimentos. No mínimo, o processo deve cobrir o seguinte: \n • Obtenção e análise de documentação de controles internos de terceiros \n • Mapeamento para o sistema de controle interno (ICS) na organização do controlador \n • Procedimentos para teste de projeto (ToD), isto é, técnicas padrão para avaliar controles \n • Procedimentos para teste de eficácia (ToE), isto é, amostragem e coleta de evidências que demonstram a eficácia dos controles de terceiros \n • Arranjos de monitoramento e revisão de logs, incluindo acessibilidade dos dados de log, desde que relacionados ao processamento de dados pessoais \n • Direitos de auditoria pontuais ou contínuos, incluindo planejamento e implantação de auditoria ",

"Sua empresa não está preparada para gerenciar notificações em tempo hábil. No mínimo, o processo de notificação às autoridades de supervisão deve incluir: \n • Procedimento de coleta / investigação de informações, descrevendo a interação entre a função DPO e outras partes da empresa e / ou serviços externos \n • Pacote de relatórios padronizado, incluindo os regulamentos mínimos de privacidade e proteção de dados ou conjunto de informações sobre normas e modelos apropriados ",

"Sua empresa não está preparada para notificar os titulares dos dados em caso de incidente ou violação. No mínimo, o processo de notificação dos titulares dos dados deve abranger: \n • Formato e modelos de relatório padronizados, adaptados e otimizados para vários canais de comunicação ( indivíduo, grupo, público) \n • Mensagens-chave predefinidas e aprovadas que expressam as ações da empresa (investigação, conseqüências, remediação, melhoria etc.) \n • Responsabilidades da organização com relação à formulação e transmissão de mensagens-chave, por exemplo, envolvimento das comunicações departamento, aconselhamento jurídico, etc. \n • Recursos de comunicação ad hoc oferecidos aos titulares dos dados, por exemplo, linha de ajuda, número de telefone gratuito, site escuro etc. " ,


"O processo de gerenciamento de incidentes e crises da sua empresa precisa de melhorias sérias. Da perspectiva dos profissionais de DPP e das unidades organizacionais que descobriram inicialmente a violação, o processo deve abranger pelo menos: \n • Descrição e documentação de fatos e números conhecidos, em um formato padronizado, onde apropriado \n • Link definido para o processo geral de escalação e alerta, geralmente definido pela função de gerenciamento de crises nos negócios (BCM) \n • Cenário de dados pessoais genéricos predefinidos para continuidade dos negócios e gerenciamento de crises, semelhante a outros cenários especiais, como ataque cibernético, pandemia, etc. \n • Relacionamentos e canais de comunicação predefinidos com atores externos, ou seja, serviços externos, como especialistas em investigação ou forense Protocolo de comunicação permanente entre unidades de linha organizacional e equipes de gerenciamento de incidentes / crises ",

"Sua empresa não está preparada para gerenciar evidências e reivindicações de forma adequada. As violações de dados pessoais representam casos de não conformidade, mas também indicam que negligência interna e / ou externa ou atividade criminosa podem estar presentes. O processo de evidências e reivindicações deve, portanto, cobrir, no mínimo : \n • Procedimentos definidos para coleta e proteção de evidências, incluindo cadeia de custódia \n • Disponibilidade de serviços especializados, como forense de TI \n • Procedimento e modelos para análise e relatório pós-incidente \n • Procedimento para fundamentar reivindicações contra terceiros, incluindo a base contratual legal para tais reclamações \n • Procedimento para preparar defesas contra reclamações de terceiros, incluindo aspectos de apelação (decisões regulatórias) \n • Link definido para relatar DPO incidente ",

"O processo de conscientização da sua empresa precisa de um trabalho significativo. No mínimo, o processo de conscientização em toda a empresa deve abranger: \n • Definição e descrição de regulamentos de privacidade e proteção de dados ou requisitos de normas nos processos organizacionais diários, incluindo exemplos de processamento de dados pessoais \n • Materiais de campanha enfatizando aspectos específicos do DPP, processamento de dados pessoais e pontos relacionados à privacidade e proteção de dados a serem observados \n • Planos de programas / projetos que estabelecem datas de destino para medidas de conscientização \n • Materiais de conscientização de terceiros e detalhes sobre como incluir terceiros em campanhas de conscientização ",

"Você informou que a equipe da sua empresa não está preparada adequadamente para cumprir suas obrigações em relação a questões de proteção e privacidade de dados. A proteção e o gerenciamento de privacidade de dados, incluindo o contexto de privacidade e proteção de dados, exigem um conjunto de habilidades e qualificações que devem ser estar presente na empresa ou contratado por meio de serviços externos.O gerenciamento de habilidades e educação é um processo essencial para garantir que os regulamentos ou normas de proteção de dados e privacidade e suas conseqüências sejam totalmente compreendidos.O processo de habilidades e educação deve incluir, mas não ser limitado para: \n • Definição de habilidades, níveis e requisitos internos para tarefas e posições relacionadas ao DPP \n • Mapeamento de habilidades para cargos e funções organizacionais (matriz) \n • Identificação de níveis de qualificação adequados e qualificações ou certificações formais, conforme necessário para cada parte da matriz \n • Caminhos de educação para diferentes funções e funções organizacionais no DPP \n • Reunir fontes, materiais e oportunidades educacionais apropriadas para o auto-estudo guiado ",


"Sua empresa carece de um processo de treinamento eficaz. O treinamento é um componente importante da conscientização geral, fornecendo oportunidades contínuas de aprendizado e reforçando as principais mensagens em torno do DPP e regulamentos ou normas de proteção de dados e privacidade. No mínimo, o processo de treinamento deve abranger: \n • Treinamento básico definido e validado sobre regulamentos de privacidade e proteção de dados, preferencialmente obrigatório para todos os membros da empresa \n • Conceito de treinamento com base na matriz de habilidades e educação \n • Plano de treinamento, geralmente anualmente, incluindo treinamento interno e externo oportunidades \n • Preparação de materiais de treinamento, para estudo guiado e auto-estudo \n • Auxílios preparatórios para treinamento de qualificações mais altas em DPP e privacidade e proteção de dados, incluindo preparação para exames de certificação, etc. \n • Fontes e fornecedores externos de treinamento definidos fins específicos, por exemplo, treinamento legal ou DPO ",

"Sua empresa não possui uma função DPO bem estabelecida. No mínimo, o processo de manutenção e execução do DPO deve abranger o seguinte: \n • Estrutura organizacional e posicionamento da função DPO, incluindo o escritório \n • DPO e seus pontos de contato em outras partes da empresa \n • Projeto de tarefas e processos administrativos para a função DPO \n • Projeto de programa de trabalho regular em um ciclo anual \n • Planejamento de recursos humanos, habilidades e necessidades educacionais ",

"Sua empresa não possui uma função DPO bem estabelecida. No mínimo, o processo de manutenção e execução do DPO deve abranger o seguinte: \n • Estrutura organizacional e posicionamento da função DPO, incluindo o escritório \n • DPO e seus pontos de contato em outras partes da empresa \n • Projeto de tarefas e processos administrativos para a função DPO \n • Projeto de programa de trabalho regular em um ciclo anual \n • Planejamento de recursos humanos, habilidades e necessidades educacionais ",


"A função DPO deve ser melhor representada em toda a empresa. O processo de gerenciamento de interfaces organizacionais deve abranger pelo menos: \n • Documentação de contatos regulares e formais em toda a empresa \n • Participação do DPO em comitês permanentes e outras reuniões institucionais formais \n • Comunicações regulares entre a função DPO e outras unidades organizacionais, incluindo atas e outros relatórios \n • Etapas do processo documentadas que exigem o envolvimento do DPO, incluindo consulta e informação (RACI) ",

"Os relatórios internos e externos formais são uma parte importante da função DPO. Sua empresa possui grandes problemas que devem ser abordados nesta área. No mínimo, o processo de gerenciamento de relatórios deve cobrir: \n • Agendamentos de relatórios para relatórios internos e externos para e pela função DPO \n • Agendamentos de relatórios para relatórios de autoridade de supervisão \n • Procedimentos que especificam modelos de relatório, conteúdo formal, frequência e distribuição, bem como classificações da CIA para relatórios \n • Procedimento de rastreamento para relatórios, abrangendo todos os agendamentos de relatórios ",

"Sua empresa não está posicionada para gerenciar regulamentos de privacidade e proteção de dados ou conformidade de normas e requisitos relacionados que são contratados por serviços externos. O processo de gerenciamento de serviços externos deve abordar, no mínimo: \n • Finalidade e substância dos serviços externos, incluindo um contrato de processamento \n • Nível de proteção definido e acordado para os serviços prestados, especificando confidencialidade, integridade e disponibilidade \n • Análise de risco do fornecedor, incluindo verificações detalhadas e due diligence, quando apropriado \n • Análise de segurança da informação \n • Direito de auditoria, análise dos resultados da revisão e rastreamento de ações corretivas \n • Verificação de antecedentes de recursos humanos, quando apropriado e permitido legalmente ",

"Os controles de aquisição de dados da sua empresa estão seriamente ausentes. No mínimo, o processo para gerenciar esses controles deve abordar: \n • Identificação de processos organizacionais que podem intencionalmente ou acidentalmente adquirir dados pessoais \n • Documentação de fluxos de dados de entrada e interfaces de dados ( por exemplo, escrito, web, outro) \n • Identificação da origem dos dados sempre que possível (por exemplo, direto do titular dos dados, controlador, processador, outros atores da cadeia de suprimentos etc.) \n • Documentação dos controles relacionados no registro de controles internos " ,

"Os controles de processamento da sua empresa estão seriamente ausentes. O processo de manutenção de tais controles deve abranger: \n • Identificação das etapas do processo, entradas e saídas que devem ser controladas \n • Identificação dos pontos de entrega para terceiros, por exemplo, processadores ou autoridades \n • Definição dos objetivos e tipos de controle (por exemplo, preventivo, detetive, corretivo) \n • Documentação dos controles relacionados no registro de controles internos ",

"Os controles de armazenamento da sua empresa estão seriamente ausentes. O processo de manutenção de tais controles deve abranger pelo menos: \n • Identificação de tipos e locais de armazenamento de dados pessoais, como mapa de armazenamento \n • Análise de instâncias de armazenamento na arquitetura geral de TI \n • Identificação de instâncias de armazenamento externo, por exemplo, de terceiros, virtualizadas, em nuvem \n • Identificação e mapeamento de pontos de transferência entre processos principais (dados em fluxo) e armazenamento (dados em repouso) \n • Documentação de controles relacionados no ambiente interno controla o registro ",

"Os controles de exclusão da sua empresa estão seriamente ausentes. O processo para manter os controles de exclusão deve cobrir pelo menos: \n • Identificação dos pontos de exclusão no sistema geral \n • Mapeamento dos controles antes da exclusão \n • Manutenção de um registro de exclusão \n • Mapeamento dos controles após a exclusão \n • Verificação da remoção do registro de dados pessoais \n • Documentação dos controles relacionados no registro de controles internos ",

"Os controles de monitoramento da sua empresa estão seriamente ausentes. O processo para manter os controles de monitoramento deve cobrir pelo menos: \n • Mapeamento do processamento de dados pessoais para o monitoramento geral, incluindo ferramentas \n • Identificação das necessidades de monitoramento no registro do processo \n • Mapeamento de relatar necessidades e aplicação aos processos de monitoramento \n • Revisão recorrente da densidade e extensão do monitoramento \n • Documentação dos controles relacionados no registro de controles internos ",

"Sua empresa não está preparada para gerenciar revisões independentes. O gerenciamento de revisões independentes requer etapas de planejamento semelhantes às revisões padrão, incluindo notificação, trabalho de campo, análise e relatório. Os profissionais e empresas do DPP podem se beneficiar da alavancagem de processos padronizados de auditoria e revisão para as revisões do DPP. Eles deve ainda vincular-se à estrutura e ao conteúdo mínimos dos relatórios do DPO, conforme estabelecido em regulamentos ou normas estabelecidas de privacidade e proteção de dados. "


];